name       : haskell-prelude-extras
version    : 0.4.0.3
release    : 2
source     :
    - http://hackage.haskell.org/package/prelude-extras-0.4.0.3/prelude-extras-0.4.0.3.tar.gz : 09bb087f0870a353ec1e7e1a08017b9a766d430d956afb88ca000a6a876bf877
license    : BSD-3-Clause
component  : programming.haskell
summary    : Higher order versions of Prelude classes to ease programming with polymorphic recursion and reduce UndecidableInstances
description: |
    Higher order versions of Prelude classes to ease programming with polymorphic recursion and reduce UndecidableInstances
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
